# Generated by Django 3.2.7 on 2021-09-24 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_creacion_columnas_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productomodel',
            name='productoNombre',
            field=models.CharField(db_column='nombre', max_length=45),
        ),
    ]
